spring.application.name=OnlineMedicalStore

# File storage
app.data.dir=data

# Thymeleaf
spring.thymeleaf.cache=false

# File Upload (for prescriptions)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Upload directory
app.upload.dir=uploads/prescriptions
